# Generated by Django 4.2.13 on 2024-07-25 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='non specified', max_length=100)),
                ('author', models.CharField(default='non specified', max_length=102)),
                ('lang', models.CharField(default='none', max_length=20)),
                ('genre', models.CharField(default='none', max_length=20)),
                ('tags', models.TextField(default='none')),
                ('bpm', models.IntegerField()),
                ('disk_image', models.ImageField(default='default/noted.jpg', upload_to='disks/')),
            ],
        ),
    ]
