# Generated by Django 4.2.13 on 2024-07-25 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoService', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='bpm',
            field=models.IntegerField(default=10),
        ),
    ]
