# Generated by Django 4.2.13 on 2024-07-25 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoService', '0002_alter_song_bpm'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='song',
            unique_together={('name', 'author')},
        ),
    ]
