# Generated by Django 4.2.13 on 2024-07-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('DjangoService', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='disk_image',
            field=models.ImageField(default='default/noted.jpg', upload_to='disks/'),
        ),
        migrations.AddField(
            model_name='song',
            name='genre',
            field=models.CharField(default='none', max_length=20),
        ),
        migrations.AlterField(
            model_name='song',
            name='lang',
            field=models.CharField(default='none', max_length=20),
        ),
    ]
